//
//  CheckStateErrorWorker.swift
//  AudibleLike
//
//  Created by Gonzalo Reyes Huertas on 7/7/17.
//  Copyright (c) 2017 Gonzalo Reyes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//  Template modified by Gabriel Lanata (http://StartApps.pe)
//

import UIKit

class CheckStateErrorWorker<T> {
    
    // MARK: - Business Logic
    
    func checkError(resultState: State<T>, completion: @escaping (State<T>) -> () ) {
        switch resultState {
        case .failure(let err):
            completion(.failure(err))
        case .success(let result):
            completion(.success(result))
        }
    }
}
