//
//  LoginModels.swift
//  AudibleLike
//
//  Created by Gonzalo Reyes Huertas on 7/7/17.
//  Copyright (c) 2017 Gonzalo Reyes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//  Template modified by Gabriel Lanata (http://StartApps.pe)
//

import UIKit

enum Login {
    
    enum FetchCheckLogin {
        struct Request {
            let loginRequestParams: [String: Any]?
        }
        struct Response {
            let resultState: State<User>!
        }
        struct ViewModel {
            let resultState: State<User>
        }
    }
    
    enum FetchCheckRegister {
        struct Request {
            let registerRequestParams: [String: Any]?
        }
        struct Response {
            let resultState: State<Bool>
            let params: [String: Any]
        }
        struct ViewModel {
            let resultState: State<Bool>
            let loginRequestparams: [String: Any]
        }
    }
        
    enum FetchPages {
        struct Request {
        }
        struct Response {
            let pages: [Page]?
        }
        struct ViewModel {
            let displayedPages: [Page]
        }
    }
}
