//
//  LoginViewController.swift
//  AudibleLike
//
//  Created by Gonzalo Reyes Huertas on 7/7/17.
//  Copyright (c) 2017 Gonzalo Reyes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//  Template modified by Gabriel Lanata (http://StartApps.pe)
//

import UIKit
import SnapKit

class LoginController: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    var interactor: LoginInteractor!
    var router: LoginRouter!
    
    // MARK: - Object Variables
    fileprivate let guideCellId = "guideCellId"
    fileprivate let loginCellId = "loginCellId"
    var pages = Page.getPages()
    
    // MARK: - Interface Objects
    var pageControlBottomConstraint: Constraint?
    var skipButtonTopConstraint: Constraint?
    var nextButtonTopConstraint: Constraint?
    
    lazy var collectionView: UICollectionView = {
        let flowLayout = UICollectionViewFlowLayout()
        flowLayout.scrollDirection = .horizontal
        flowLayout.minimumLineSpacing = 0
        let cv = UICollectionView(frame: .zero, collectionViewLayout: flowLayout)
        cv.bounces = false
        cv.showsHorizontalScrollIndicator = false
        cv.isPagingEnabled = true
        cv.delegate = self
        cv.dataSource = self
        return cv
    }()
    
    lazy var pageControl: UIPageControl = {
        let pc = UIPageControl()
        //color for the circles
        pc.pageIndicatorTintColor = .lightGray
        pc.numberOfPages = self.pages.count + 1
        pc.isUserInteractionEnabled = false
        //this color looks cool-orange
        pc.currentPageIndicatorTintColor = orangeColor
        return pc
    }()
    
    let skipButton: UIButton = {
        let button = UIButton()
        button.setTitle("Skip", for: .normal)
        button.setTitleColor(orangeColor, for: .normal)
        button.addTarget(self, action: #selector(skip), for: .touchUpInside)
        return button
    }()
    
    lazy var nextButton: UIButton = {
        let button = UIButton()
        button.setTitle("Next", for: .normal)
        button.setTitleColor(orangeColor, for: .normal)
        button.addTarget(self, action: #selector(nextPage), for: .touchUpInside)
        return button
    }()
    
    // MARK: - View Lifecycle
    override func viewDidLoad() {
        LoginConfigurator.configure(viewController: self)
        super.viewDidLoad()
        setupViews()
        registerCells()
        observeKeyboardNotification()
    }
    
    // MARK: - Setup Views
    fileprivate func setupViews() {
        view.addSubview(collectionView)
        view.addSubview(pageControl)
        view.addSubview(skipButton)
        view.addSubview(nextButton)
        collectionView.snp.makeConstraints { (make) in
            make.edges.equalTo(view)
        }
        pageControl.snp.makeConstraints { (make) in
            pageControlBottomConstraint = make.bottom.equalTo(view).constraint
            make.left.right.equalTo(view)
            make.height.equalTo(40)
        }
        skipButton.snp.makeConstraints { (make) in
            skipButtonTopConstraint = make.top.equalTo(view).offset(16).constraint
            make.left.equalTo(view)
            make.height.equalTo(50)
            make.width.equalTo(60)
        }
        nextButton.snp.makeConstraints { (make) in
            nextButtonTopConstraint = make.top.equalTo(view).offset(16).constraint
            make.right.equalTo(view)
            make.height.width.equalTo(skipButton)
        }
    }
    
    fileprivate func registerCells() {
        collectionView.register(GuideCell.self, forCellWithReuseIdentifier: guideCellId)
        collectionView.register(LoginCell.self, forCellWithReuseIdentifier: loginCellId)
    }
    
    fileprivate func moveControlConstraintsOffScreen() {
        pageControlBottomConstraint?.update(offset: 40)
        skipButtonTopConstraint?.update(offset: -60)
        nextButtonTopConstraint?.update(offset: -60)
    }
    
    // MARK: - Handle Actions
    func skip() {
        pageControl.currentPage = pages.count - 1
        nextPage()
    }
    
    func nextPage() {
        //last page
        if pageControl.currentPage == pages.count {return}
        
        //second last page
        if pageControl.currentPage == pages.count - 1{
            moveControlConstraintsOffScreen()
            
            UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
                
                self.view.layoutIfNeeded()
                
            }, completion: nil)
            
        }
        
        let indexPath = IndexPath(item: pageControl.currentPage + 1, section: 0)
        collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: true)
        pageControl.currentPage += 1
    }
    
    // MARK: - Observe Keyboard Methods
    fileprivate func observeKeyboardNotification() {
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardShow), name: .UIKeyboardWillShow, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardHide), name: .UIKeyboardWillHide, object: nil)
        
    }
    
    func keyboardShow() {
        UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
            
            self.view.frame = CGRect(x: 0, y: -50, width: self.view.frame.width, height: self.view.frame.height)
        }, completion: nil)
    }
    
    func keyboardHide() {
        UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
            
            self.view.frame = CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height)
        }, completion: nil)
    }
    
    // MARK: - CollectionView Methods
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        //use when the keyboard has to go away no matter what
        view.endEditing(true)
    }
    
    func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        //this is equal to the "page's number"
        let pageNumber = Int(targetContentOffset.pointee.x / view.frame.width)
        pageControl.currentPage = pageNumber
        
        if pageNumber == pages.count {
            moveControlConstraintsOffScreen()
        }else {
            pageControlBottomConstraint?.update(offset: 0)
            skipButtonTopConstraint?.update(offset: 16)
            nextButtonTopConstraint?.update(offset: 16)
        }
        
        UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 1, initialSpringVelocity: 1, options: .curveEaseOut, animations: {
            
            self.view.layoutIfNeeded()
            
        }, completion: nil)
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return pages.count + 1
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        //if cell index = 3, which is the last one
        if indexPath.item == pages.count{
            let loginCell = collectionView.dequeueReusableCell(withReuseIdentifier: loginCellId, for: indexPath) as! LoginCell
            loginCell.delegate = router
            return loginCell
        }
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: guideCellId, for: indexPath) as! GuideCell
        let page = pages[indexPath.item]
        cell.page = page
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: view.frame.width, height: view.frame.height)
    }
    
    
    // MARK: - Event handling
    func fetchPagesInfo() {
        let request = Login.FetchPages.Request()
        interactor.fetchPages(request: request)
    }
    
    func checkLogin(params: [String: Any]) {
        let request = Login.FetchCheckLogin.Request(loginRequestParams: params)
        interactor.checkLogin(request: request)
    }
    
    func checkRegister(params: [String: Any]) {
        let request = Login.FetchCheckRegister.Request(registerRequestParams: params)
        interactor.checkRegister(request: request)
    }
    
    // MARK: - Display logic
    func displayPages(viewModel: Login.FetchPages.ViewModel) {
        pages = viewModel.displayedPages
    }
    
    func fetchLogin(viewModel: Login.FetchCheckLogin.ViewModel) {
        switch viewModel.resultState {
        case .failure(_):
            let alert = UIAlertController(title: "Error", message: "Se produjo un error interno", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return
            
        case .success(let user):
            if user.username.isEmpty {
                let alert = UIAlertController(title: "Error", message: "El usuario no existe", preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
                self.present(alert, animated: true, completion: nil)
                return
            }
            router.navigateToHome(user: user)
        }
    }
    
    func fetchRegister(viewModel: Login.FetchCheckRegister.ViewModel) {
        switch viewModel.resultState {
        case .failure(_):
            let alert = UIAlertController(title: "Error", message: "Se produjo un error interno", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return
            
        case .success(let result):
            switch result {
            case false:
                let alert = UIAlertController(title: "Error", message: "Usuario inválido", preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: nil))
                self.present(alert, animated: true, completion: nil)
                return
                
            case true:
                checkLogin(params: viewModel.loginRequestparams)
            }
        }
    }
}
