//
//  LoginPresenter.swift
//  AudibleLike
//
//  Created by Gonzalo Reyes Huertas on 7/7/17.
//  Copyright (c) 2017 Gonzalo Reyes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//  Template modified by Gabriel Lanata (http://StartApps.pe)
//

import UIKit

class LoginPresenter {
    
    weak var viewController: LoginController!
    
    // MARK: - Presentation logic    
    func presentPages(response: Login.FetchPages.Response) {
        let viewModel = Login.FetchPages.ViewModel(displayedPages: response.pages ?? [])
        viewController.displayPages(viewModel: viewModel)
    }
    
    func presentCheckLogin(response: Login.FetchCheckLogin.Response) {
        let viewModel = Login.FetchCheckLogin.ViewModel(resultState: response.resultState!)
        viewController.fetchLogin(viewModel: viewModel)
    }
    
    func presentCheckRegister(response: Login.FetchCheckRegister.Response) {
        let viewModel = Login.FetchCheckRegister.ViewModel(resultState: response.resultState, loginRequestparams: ["username": response.params["username"], "password": response.params["password"]])
        viewController.fetchRegister(viewModel: viewModel)
    }
    
}
